project_id = "mnefxebwbvxrvowkwkjy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[db]
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true
